name: Docker Image CI

on:
  push:
    branches: [ "custom" ]
  pull_request:
    branches: [ "custom" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    env:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      TRAVIS_COMMIT: ${{ github.head_ref }}
    steps:
    - uses: actions/checkout@v3
    - name: Build and publish the Docker image
      run: bash docker-build-push.sh
