name: Docker Image CI

on:
  push:
    branches: [ "custom" ]
  pull_request:
    branches: [ "custom" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    env:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    outputs:
      image_tag: ${{ steps.output_tag.outputs.tag }}
    steps:
    - uses: actions/checkout@v3
    - name: Add SHORT_SHA env property with commit short sha
      run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
    - name: Generate the Version
      run: echo "VERSION=`echo $(cat package.json | jq .version -r)-custom-$SHORT_SHA`" >> $GITHUB_ENV
    - name: Print the Version
      run: echo $VERSION
    - name: Build the Docker image
      run: docker build . --tag yukimir/jinrou:$VERSION
    - name: Login to DockerHub
      run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - name: Push to Dockerhub
      run: docker push yukimir/jinrou:$VERSION
    - name: Output the Tag
      id: output_tag
      run: echo "::set-output name=tag::yukimir/jinrou:$VERSION"
  publish:
    runs-on: ubuntu-latest
    environment: production
    env:
      KUBEXXX: XXX
    needs: build
    steps:
      - name: Print Image Tag
        run: echo ${{ needs.build.outputs.image_tag }}